version: '3'
services:
  app:
    image: "${APP_IMAGE}"
    restart: "always"
    tty: true
    env_file:
      - .env
    ports:
      - "${APP_PORT}:{APP_PORT}"
    volumes:
      - .env/:/opt/app/.env
