version: '3'
services:
  app:
    image: ghcr.io/gusnitrous/nestjs-scrum-poker-online:main
    restart: "always"
    tty: true
    env_file:
      - .env
    ports:
      - "${APP_PORT}:{APP_PORT}"
    volumes:
      - .env/:/opt/app/.env
